name: Continuous Integration & Deployment

on:
  push:

jobs:
  pipeline_development:
    name: Pipeline Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies [PYTEST]
        run: pip install pytest pytest-md pytest-emoji

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Code Quality [LINT]
        uses: chartboost/ruff-action@v1

      - name: Code Quality [PYTEST]
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'