name: Continuous Integration & Deployment

on:
  push:

jobs:
  pipeline_development:
    name: Pipeline Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Code Quality [LINT]
        uses: chartboost/ruff-action@v1

      - name: Code Quality [PYTEST]
        uses: JotaFan/pycoverage@v1.0.0
        with:
          cov-omit-list: tests/*
          cov-threshold-single: 85
          cov-threshold-total: 90
          async-tests: true
          poetry-version: 1.8.3